spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.103:3306/jdbc
  #打印执行的sql
  jpa:
    show-sql: true
    ## 表不存在就更新，表结构改变也更新，否则不变
    hibernate:
      ddl-auto: update
